FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
ARG SCTTA_DB_USER_ARG
ARG SCTTA_DB_PASS_ARG
ARG SCTTA_DB_NAME_ARG
ARG SCTTA_DB_HOST_ARG="192.168.99.100"
ARG SCTTA_DB_PORT_ARG="5432"
ARG SCTTA_DB_ADAPTER_ARG="postgresql"
ARG SCTTA_HBT_DIALECT_PACKAGE_ARG="org.hibernate.dialect.PostgreSQLDialect"
COPY ${JAR_FILE} app.jar
# ENV vars with default values
ENV SCTTA_DB_HOST=$SCTTA_DB_HOST_ARG SCTTA_DB_PORT=$SCTTA_DB_PORT_ARG SCTTA_DB_ADAPTER=$SCTTA_DB_ADAPTER_ARG SCTTA_HBT_DIALECT_PACKAGE=$SCTTA_HBT_DIALECT_PACKAGE_ARG SCTTA_JPA_HBT_FORMAT_SQL="false" SCTTA_JPA_SHOW_SQL="false" SCTTA_LOG_LEVEL="INFO"
# ENV vars to be set explicitly (on build or run time)
ENV SCTTA_DB_USER=$SCTTA_DB_USER_ARG SCTTA_DB_PASS=$SCTTA_DB_PASS_ARG SCTTA_DB_NAME=$SCTTA_DB_NAME_ARG
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]

